export const CardAssets: Record<string, any> = {
  // Spades
  'SA': require('../../assets/cards/Spades 1.png'),
  'S2': require('../../assets/cards/Spades 2.png'),
  'S3': require('../../assets/cards/Spades 3.png'),
  'S4': require('../../assets/cards/Spades 4.png'),
  'S5': require('../../assets/cards/Spades 5.png'),
  'S6': require('../../assets/cards/Spades 6.png'),
  'S7': require('../../assets/cards/Spades 7.png'),
  'S8': require('../../assets/cards/Spades 8.png'),
  'S9': require('../../assets/cards/Spades 9.png'),
  'S10': require('../../assets/cards/Spades 10.png'),
  'SJ': require('../../assets/cards/Spades 11.png'),
  'SQ': require('../../assets/cards/Spades 12.png'),
  'SK': require('../../assets/cards/Spades 13.png'),

  // Diamonds
  'DA': require('../../assets/cards/Diamonds 1.png'),
  'D2': require('../../assets/cards/Diamonds 2.png'),
  'D3': require('../../assets/cards/Diamonds 3.png'),
  'D4': require('../../assets/cards/Diamonds 4.png'),
  'D5': require('../../assets/cards/Diamonds 5.png'),
  'D6': require('../../assets/cards/Diamonds 6.png'),
  'D7': require('../../assets/cards/Diamonds 7.png'),
  'D8': require('../../assets/cards/Diamonds 8.png'),
  'D9': require('../../assets/cards/Diamonds 9.png'),
  'D10': require('../../assets/cards/Diamonds 10.png'),
  'DJ': require('../../assets/cards/Diamonds 11.png'),
  'DQ': require('../../assets/cards/Diamonds 12.png'),
  'DK': require('../../assets/cards/Diamonds 13.png'),

  // Hearts
  'HA': require('../../assets/cards/Hearts 1.png'),
  'H2': require('../../assets/cards/Hearts 2.png'),
  'H3': require('../../assets/cards/Hearts 3.png'),
  'H4': require('../../assets/cards/Hearts 4.png'),
  'H5': require('../../assets/cards/Hearts 5.png'),
  'H6': require('../../assets/cards/Hearts 6.png'),
  'H7': require('../../assets/cards/Hearts 7.png'),
  'H8': require('../../assets/cards/Hearts 8.png'),
  'H9': require('../../assets/cards/Hearts 9.png'),
  'H10': require('../../assets/cards/Hearts 10.png'),
  'HJ': require('../../assets/cards/Hearts 11.png'),
  'HQ': require('../../assets/cards/Hearts 12.png'),
  'HK': require('../../assets/cards/Hearts 13.png'),

  // Clubs
  'CA': require('../../assets/cards/Clubs 1.png'),
  'C2': require('../../assets/cards/Clubs 2.png'),
  'C3': require('../../assets/cards/Clubs 3.png'),
  'C4': require('../../assets/cards/Clubs 4.png'),
  'C5': require('../../assets/cards/Clubs 5.png'),
  'C6': require('../../assets/cards/Clubs 6.png'),
  'C7': require('../../assets/cards/Clubs 7.png'),
  'C8': require('../../assets/cards/Clubs 8.png'),
  'C9': require('../../assets/cards/Clubs 9.png'),
  'C10': require('../../assets/cards/Clubs 10.png'),
  'CJ': require('../../assets/cards/Clubs 11.png'),
  'CQ': require('../../assets/cards/Clubs 12.png'),
  'CK': require('../../assets/cards/Clubs 13.png'),

  // Backs
  'back1': require('../../assets/cards/Card Back 1.png'),
  'back2': require('../../assets/cards/Card Back 2.png'),
  'back3': require('../../assets/cards/Card Back 3.png'),
};
